<a href="https://colab.research.google.com/github/xanasa14/DataScienceSheetCheats/blob/main/SheetcheatPD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Important recognition to https://www.machinelearningplus.com/python/101-pandas-exercises-python/ for putting everything together 
#Some methods are deprecated. I updated them in this Colab. 
import numpy as np 
import pandas as pd 


In [ ]:

#2 How to create a series from a list, numpy array and dict?
'''Create a pandas series from each of the items below: a list, numpy and a dictionary Input

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))'''
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

# Solution
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
ser3

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [ ]:
#3. How to convert the index of a series into a column of a dataframe?
# Solution
df = ser3.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [ ]:
#4. How to combine many series to form a dataframe?
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))


# Solution 
df = pd.DataFrame({'col1': ser1, 'col2': ser2})

print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


In [ ]:
#5. How to assign name to the series’ index?
ser.name = 'alphabets'
ser.head()

0    -1.916373
1     0.397661
2    -2.230446
3    29.490942
4     3.411988
Name: alphabets, dtype: float64

In [ ]:
#6. How to get the items of series A not present in series B?
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution
ser1[~ser1.isin(ser2)]

In [ ]:
#7. How to get the items not common to both series A and series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
# Solution
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

In [ ]:
#8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
# Input
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

# Solution
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [ ]:
#9. How to get frequency counts of unique items of a series?
# Input
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

# Solution
ser.value_counts()

d    7
h    6
a    4
g    4
b    3
c    2
f    2
e    2
dtype: int64

In [ ]:
#10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
# Input
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Solution
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq: 1    5
4    3
2    3
3    1
dtype: int64


0         4
1         4
2         1
3     Other
4         4
5     Other
6         1
7         1
8     Other
9     Other
10        1
11        1
dtype: object

In [ ]:
#11. How to bin a numeric series to 10 groups of equal size?
# Input
ser = pd.Series(np.random.random(20))
print(ser.head(10))

# Solution
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()

0    0.789806
1    0.307398
2    0.746696
3    0.318541
4    0.891209
5    0.475945
6    0.505793
7    0.133092
8    0.195532
9    0.190104
dtype: float64


0     9th
1     4th
2     8th
3     4th
4    10th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [ ]:
#12. How to convert a numpy array to a dataframe of given shape? (L1)
# Input
ser = pd.Series(np.random.randint(1, 10, 20))
print(ser)
# Solution
df = pd.DataFrame(ser.values.reshape(4,5))
print(df)

0     2
1     8
2     3
3     6
4     4
5     8
6     2
7     5
8     6
9     1
10    9
11    4
12    8
13    3
14    1
15    4
16    2
17    4
18    5
19    4
dtype: int64
   0  1  2  3  4
0  2  8  3  6  4
1  8  2  5  6  1
2  9  4  8  3  1
3  4  2  4  5  4


In [ ]:
#13. How to find the positions of numbers that are multiples of 3 from a series?
# Input
ser = pd.Series(np.random.randint(1, 10, 7))
ser

# Solution
print(ser)
result = np.where(ser % 3==0)
result

0    3
1    1
2    6
3    6
4    6
5    8
6    1
dtype: int64


(array([0, 2, 3, 4]),)

In [ ]:
#14. How to extract items at given positions from a series
# Input
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [ ]:
#15. How to stack two series vertically and horizontally ?
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
ser1.append(ser2)

# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [ ]:
#16. How to get the positions of items of series A in another series B?
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
print(ser1)
print(ser2)
# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]
# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]


0    10
1     9
2     6
3     5
4     3
5     1
6    12
7     8
8    13
dtype: int64
0     1
1     3
2    10
3    13
dtype: int64


[5, 4, 0, 8]

In [ ]:
#17. How to compute the mean squared error on a truth and predicted series?
# Input
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Solution
np.mean((truth-pred)**2)

0.419654473789171

In [ ]:
#18. How to convert the first character of each element in a series to uppercase?
# Input
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [ ]:
#19. How to calculate the number of characters in each word in a series?
# Input
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [ ]:
#20. How to compute difference of differences between consequtive numbers of a series?
# Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

# Solution
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [ ]:
#21. How to convert a series of date-strings to a timeseries?
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [ ]:
#22. How to get the day of month, week number, day of year and day of week from a series of date strings?
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.day_of_week.to_list())




Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  [4, 2, 5, 3, 0, 5]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  del sys.path[0]


In [ ]:
#23. How to convert year-month string to dates corresponding to the 4th day of the month?
import pandas as pd
# Input
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))

# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# Format it.
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [ ]:
#24. How to filter words that contain atleast 2 vowels from a series?
# Input
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [ ]:
#25. How to filter valid emails from a series?
# Input
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

# Solution 1 (as series of strings)
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

# Solution 2 (as series of list)
emails.str.findall(pattern, flags=re.IGNORECASE)

# Solution 3 (as list)
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [ ]:
#26. How to get the mean of a series grouped by another series?
# Input
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(fruit.tolist())
print(weights.tolist())

# Solution
weights.groupby(fruit).mean()

['carrot', 'banana', 'apple', 'apple', 'apple', 'banana', 'banana', 'carrot', 'apple', 'banana']
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]


apple     5.25
banana    6.25
carrot    4.50
dtype: float64

In [ ]:
#27. How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution 
sum((p - q)**2)**.5

# Solution (using func)
np.linalg.norm(p-q)

18.16590212458495

In [ ]:
#28. How to find all the local maxima (or peaks) in a numeric series?
# Input
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7])

In [ ]:
#29 How to replace missing spaces in a string with the least frequent character?
# Input
my_str = 'dbc deb abed gade'

# Solution
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
res = "".join(ser.replace(' ', least_freq))
res

d    4
b    3
     3
e    3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

In [ ]:
#30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
# Solution
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    7
2000-01-08    6
2000-01-15    7
2000-01-22    8
2000-01-29    4
2000-02-05    3
2000-02-12    1
2000-02-19    1
2000-02-26    7
2000-03-04    6
Freq: W-SAT, dtype: int64

In [ ]:
#31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
# Input
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [ ]:
#32. How to compute the autocorrelations of a numeric series?
# Input
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
print(ser)
# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

0     -1.916373
1      0.397661
2     -2.230446
3     29.490942
4      3.411988
5     13.644542
6     12.080996
7     21.901739
8      6.730772
9     19.495241
10    -4.770292
11    23.528087
12    32.587260
13    22.926126
14     3.840161
15    19.902577
16    41.982091
17    18.479277
18    12.308592
19    37.984899
dtype: float64
[0.02, -0.05, 0.13, 0.65, -0.06, 0.12, 0.0, 0.4, 0.19, 0.34]
Lag having highest correlation:  4


In [ ]:
#33. How to import only every nth row from a csv file to create a dataframe?
# Solution 1: Use chunks and for-loop
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])


# Solution 2: Use chunks and list comprehension
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
'''
# Solution 3: Use csv reader
import csv          
with open('BostonHousing.csv', 'r') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):
        if i%50 == 0:
            out.append(row)
df2 = pd.DataFrame(out[1:], columns=out[0])
'''

print(df2.head())

        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  


In [ ]:
#34. How to change column values when importing csv to a dataframe?
# Solution 1: Using converter parameter
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})


'''# Solution 2: Using csv reader
import csv
with open('BostonHousing.csv', 'r') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):
        if i > 0:
            row[13] = 'High' if float(row[13]) > 25 else 'Low'
        out.append(row)

df = pd.DataFrame(out[1:], columns=out[0])'''
print(df.head())

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


In [ ]:
#35. How to create a dataframe with rows as strides from a given series?
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [ ]:
#36. How to import only specified columns from a csv file?
df2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df2.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [ ]:
#37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#  number of rows and columns
print(df.shape)

# datatypes
print(df.dtypes)

# how many columns under each dtype
print(df.dtypes.value_counts())
print(df.dtypes.value_counts())

# summary statistics
df_stats = df.describe()

# numpy array 
df_arr = df.values

# list
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64
float64    18
object      9
dtype: int64


In [ ]:
#38. How to extract the row and column number of a particular cell with given criterion?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

# Get the value
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

# Alternates
df.at[row[0], 'Price']
df._get_value(row[0], 'Price')



# The difference between `iat` - `iloc` vs `at` - `loc` is:
# `iat` snd `iloc` accepts row and column numbers. 
# Whereas `at` and `loc` accepts index and column names.


61.9

In [ ]:
#39. How to rename a specific columns in a dataframe?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Step 1:
df=df.rename(columns = {'Type':'CarType'})
# or
df.columns.values[2] = "CarType"

# Step 2:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [ ]:
#40. How to check if a dataframe has any missing values?

# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df.isnull().values.any()

True

In [ ]:
#41. How to count the number of missing values in each column?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Solution
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

23

In [ ]:
#42. How to replace missing values of multiple numeric columns with the mean?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [ ]:
#43. How to use apply function on existing columns with global variables as additional arguments?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df[['Min.Price', 'Max.Price']]

Min.Price  Max.Price
0   12.900000      18.80
1   29.200000      38.70
2   25.900000      32.30
3   17.118605      44.60
4   17.118605      19.15
..        ...        ...
88  16.600000      22.70
89  17.600000      22.40
90  22.900000      23.70
91  21.800000      23.50
92  24.800000      28.50

[93 rows x 2 columns]

In [ ]:
#44. How to select a specific column from a dataframe as a dataframe instead of a series?
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

# Alternately the following returns a Series
type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])

pandas.core.series.Series

In [ ]:
#45. How to change the order of columns of a dataframe?
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)

In [ ]:
#46. How to set the number of rows and columns displayed in the output?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df


Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [ ]:
#47. How to format or suppress scientific notations in a pandas dataframe?
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)

# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
# or
df.applymap(lambda x: '%.4f' % x)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0297
1  0.0000
2  0.0012
3  0.0002


In [ ]:
#48. How to format all the values in a dataframe as percentages?
# Input
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

In [ ]:
#49. How to filter every nth row in a dataframe?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [ ]:
#50. How to create a primary key index by combining relevant columns?
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [ ]:
#51. How to get the row number of the nth largest value in a column?
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
# Solution
n = 5
df['a'].argsort()[::-1][n]
df.head(10)
df['a'].argsort()[::-1][n]


1

In [ ]:
#52. How to find the position of the nth largest value greater than a given value?
# Input
ser = pd.Series(np.random.randint(1, 100, 15))

# Solution
#computing row number of nth largest value in column "b"
result = df['b'].argsort()[::-1][n]

print(df)

print("Row number in b:", result)

    a   b   c
0  20  15  26
1  22  17  10
2   5   7  19
3  29  25  22
4  20   7   9
5  21  29  20
6  24  19  10
7   3   1   1
8  22  20   4
9  26   1  15
Row number in b: 1


In [ ]:
#53. How to get the last n rows of a dataframe with row sum > 100?
# Input
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution
# print row sums
rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
last_two_rows


0   1   2   3
6  14  31  37  37
9  27  13  33  29

In [ ]:
#54. How to find and cap outliers from a series or dataframe column?
# Input
ser = pd.Series(np.logspace(-2, 2, 30))

# Solution
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)
print(ser.to_list())
capped_ser = cap_outliers(ser, .05, .95)

[0.01, 0.01373823795883263, 0.018873918221350976, 0.02592943797404667, 0.035622478902624426, 0.04893900918477494, 0.06723357536499334, 0.09236708571873861, 0.12689610031679222, 0.17433288221999882, 0.2395026619987486, 0.32903445623126676, 0.4520353656360243, 0.6210169418915616, 0.8531678524172805, 1.1721022975334805, 1.6102620275609392, 2.212216291070448, 3.039195382313198, 4.175318936560401, 5.736152510448681, 7.880462815669913, 10.82636733874054, 14.873521072935118, 20.433597178569418, 28.072162039411758, 38.56620421163472, 52.98316906283707, 72.78953843983146, 100.0]
0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.87667222018393


In [ ]:
#55. How to reshape a dataframe to the largest possible square after removing the negative values?
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)


    0   1   2   3   4   5   6   7   8   9
0  25 -12 -11 -17   6   8  38  22  17  48
1 -10  43  31 -20 -17  45  42  36  38  48
2  24  -3  18  27  28  47  13   8   7   8
3  24 -11 -16 -18  -1  10  27  46 -15  17
4  47  -8  38  23  21  41  38  24 -11  29
5   8 -16  34  43  48   1   0 -13 -17  30
6 -12 -19 -12  41  21  43 -15  -7  44  24
7 -16  23 -18  49  -7 -20  42  12  31  30
8   3   1  30  18  36  34  18   0 -12   3
9 -11  28  -9  41  -4  14 -17  14  42  44
[[25.  6.  8. 38. 22. 17. 48. 43.]
 [31. 45. 42. 36. 38. 48. 24. 18.]
 [27. 28. 47. 13.  8.  7.  8. 24.]
 [10. 27. 46. 17. 47. 38. 23. 21.]
 [41. 38. 24. 29.  8. 34. 43. 48.]
 [30. 41. 21. 43. 44. 24. 23. 49.]
 [42. 12. 31. 30. 30. 18. 36. 34.]
 [18.  3. 28. 41. 14. 14. 42. 44.]]


In [9]:
#56. How to swap two rows of a dataframe?
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

#print(swap_rows(df, 1, 2))
df
swappedDF = swap_rows(df, 1, 2)
swappedDF

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [10]:
#57. How to reverse the rows of a dataframe?
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [11]:
#58. How to create one-hot encodings of a categorical variable (dummy variables)?
# Input
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [12]:
#59. Which column contains the highest number of row-wise maximum values?
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  0


In [13]:
#60. How to create a new column that contains the row number of nearest column by euclidean distance?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Solution
import numpy as np

# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

In [14]:
#61. How to know the maximum possible correlation value of each column against other columns?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

# Solution
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.57 0.66 0.88 0.64 0.88 0.64 0.55 0.62 0.64 0.66]


In [15]:
#62. How to create a column containing the minimum by maximum of each row?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)

In [16]:
#63. How to create a column that contains the penultimate value in each row?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4   5   6   7   8   9  penultimate
0  13  50  17  38  23  56  11  61  11  72           61
1  25  96  19  39  20  39  77  96  33  30           77
2  88  70  80  68   4  70  47  75  42  70           80
3  43  74  67   5  73   8  94  67  60  99           94
4  40  43  89  79  97  50  66  40  62  98           97
5  19  71  15  69  63  65  39  94  71  82           82
6  16  55  24  32  47   9  70  70  56  10           56
7  79  53  24  39   4  83  79  10  37  89           83


In [17]:
#64. How to normalize all columns in a dataframe?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0  0.87  1.06 -0.65 -1.54  1.46  1.11 -0.84  1.09  0.99  1.12
1  0.71  0.78 -1.28  1.32 -1.29  1.31 -0.84 -0.75 -0.91 -0.38
2  1.39  0.62 -0.36 -0.27  0.41 -0.26 -1.08 -0.67  1.08 -0.05
3 -0.92  0.93  1.42  0.77 -1.03  0.18 -0.65 -0.92 -1.47 -0.50
4 -1.38 -1.18  1.17  0.73 -0.58 -1.92  1.08  1.15 -0.58 -0.92
5  0.55 -0.98  0.67  0.45 -0.39 -0.26  0.09 -0.75  0.28  1.31
6 -0.50  0.06  0.01 -1.18  0.22 -0.40  0.71  1.35 -0.49 -1.43
7 -0.72 -1.29 -0.99 -0.27  1.20  0.23  1.52 -0.49  1.11  0.85
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.19  0.00  0.77  1.00  0.00  0.06  0.90  0.11  0.05  0.07
1  0.25  0.12  1.00  0.00  1.00  0.00  0.90  0.92  0.78  0.62
2  0.00  0.18  0.66  0.56  0.38  0.48  1.00  0.89  0.01  0.49
3  0.84  0.05  0.00  0.19  0.90  0.35  0.83  1.00  1.00  0.66
4  1.00  0.96  0.09  0.21  0.74  1.00  0.17  0.09  0.66  0.81
5  0.31  0.87  0.28  0.30  0.67  0.48  0.55 

In [18]:
#65. How to compute the correlation of each row with the suceeding row?
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[0.24, 0.37, -0.03, 0.01, -0.13, 0.59, 0.38]

In [30]:
#66. How to replace both the diagonals of dataframe with 0?
# Input
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
df

0   1   2   3   4   5   6   7   8   9
0   0  53  42  10  93  98  30  60  66   0
1  83   0  99  46   5  31  13  16   0  60
2  91  93   0  43  69  34  94   0  37  24
3  17  88  38   0   1  54   0  68  64  12
4  76  70  13   4   0   0  11  50  11  47
5  61  89  16   2   0   0  96  44  98  21
6  73  45  71   0  42  29   0  33  34  39
7  33  32   0  74  56  81  91   0  32  42
8  66   0  71  60  60  46  85  87   0  56
9   0  69  25  16  40  25  22  49  64   0

In [31]:
#67. How to get the particular group of a groupby dataframe by key?
# Input
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

# Solution 1
df_grouped.get_group('apple')

# Solution 2
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)

    col1      col2  col3
0  apple  0.322998     8
3  apple  0.647791     2
6  apple  0.021330     1


In [34]:
#68. How to get the n’th largest value of a column when grouped by another column?
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-1]

    fruit     taste  price
0   apple  0.429693      3
1  banana  0.094036     12
2  orange  0.720758     10
3   apple  0.962146      9
4  banana  0.000958      1
5  orange  0.969112      5
6   apple  0.071676      8
7  banana  0.553827     10
8  orange  0.815642     13


0.5538269922336878

In [35]:
#69. How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Solution
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit     price
0   apple  9.666667
1  banana  4.333333
2  orange  9.000000


In [39]:
#70. How to join two dataframes by 2 columns so they have only the common rows?
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

# Solution
pd.merge(df1, df2, how='inner', left_on=['fruit'], right_on=['pazham'], suffixes=['_left', '_right'])

fruit weight  price_left  pazham  kilo  price_right
0    apple   high           6   apple  high           12
1    apple   high           6   apple   low           14
2    apple   high          13   apple  high           12
3    apple   high          13   apple   low           14
4    apple   high          14   apple  high           12
5    apple   high          14   apple   low           14
6   orange    low           1  orange   low            8
7   orange    low           1  orange  high            0
8   orange    low          12  orange   low            8
9   orange    low          12  orange  high            0
10  orange    low           1  orange   low            8
11  orange    low           1  orange  high            0

In [40]:
#71. How to remove rows from a dataframe that are present in another dataframe?
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})


# Solution
print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8


In [41]:
#72. How to get the positions where values of two columns match?
# Input
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1 == df.fruit2)

(array([3, 6, 9]),)

In [42]:
#74. How to get the frequency of unique values in the entire dataframe?
# Input
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
pd.value_counts(df.values.ravel())

3    4
4    4
2    4
6    3
8    2
5    2
9    1
dtype: int64

In [43]:
#75. How to split a text column into two separate columns?
# Input
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

# Solution
df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
